### ISSUE TITLE
Does not detect TODO when encoded in Multiline comment

### ISSUE THREAD

**Issue by arkeo01** [Gruntfuggly/todo-tree#375] opened 2020-10-13 20:32 UTC
Detects
`// TODO: 1. Build it`

Does not Detect
```
/*
*
* TODO: 1 Build it
*
*/
```

**Comment by Gruntfuggly** [comment] 2020-10-13 20:38
Please see the section in the README about multiline todos:
https://github.com/Gruntfuggly/todo-tree#multiline-todos

**Comment by arkeo01** [comment] 2020-10-13 20:43
Why not include todos between multiline comments instead of just at the start? It is always great to have a flexible usage!

**Comment by arkeo01** [comment] 2020-10-13 20:48
I am thinking of contributing to this issue anyways! Only if you think it would be a good addition to the existing usage...

**Comment by Gruntfuggly** [comment] 2020-10-13 20:49
Have you tried the multiline regex? 

It works, but is not enabled by default as not everybody needs it and adds a large overhead on the processing.

**Comment by arkeo01** [comment] 2020-10-13 20:55
No I haven't tried multi-line regex... Do one thing assign this PR to me, I'll see whether there is a way around it, if not you can always close the issue anyways :P

**Comment by Gruntfuggly** [comment] 2020-10-13 20:56
Why do you need a way round it? It already works - please try the multiline regex.

**Comment by arkeo01** [comment] 2020-10-13 21:00
But it is not detecting TODO when commented as above? What am I missing?

**Comment by Gruntfuggly** [comment] 2020-10-13 21:07
What regex are you using? You'll need something like:
```
"todo-tree.regex.regex": "(?:(?://|#|<!--|;|/\\*\\*?|\\*)\\s*($TAGS)|^\\s*- \\[ \\])"
```
which works for your example.

For more examples see:
https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples#multiline-regexs

Sorry, but multiline regexes are complicated, which is one of the reasons it's not enabled by default.

**Comment by Gruntfuggly** [comment] 2020-10-15 09:41
Did you manage to get it to work?

**Comment by SrBrahma** [comment] 2020-10-19 01:48
Doesn't VsCode output some info to tell if the line is a comment? Because the comments are coloured. Maybe it would be faster.

Also, if performance is a concern, the extension could run specific regexes for known files extension. For unknown extensions, would run the current regex.

I only use TODO in .jsx?/.tsx?. Having a regex check for // pattern and other for multiline /** */ surely wouldn't be a performance issue

**Comment by Gruntfuggly** [comment] 2020-10-19 07:46
The extension search files - it doesn't open each file and parse it for comments. 

Running individual regexes for each file type would be much worse for performance. If you want to limit the files which are searched, then that is fully supported.

The default regex is quite simple by design - vscode provides support for many languages, so it would be impossible for the extension to work with all of them out of the box. Why would a C++ developer want to search files for python comments, for example?

If you want to use multiline TODO's you can - you just have to change the regex - there are instructions in the README.md (https://github.com/Gruntfuggly/todo-tree#multiline-todos) and also examples in the wiki (https://github.com/Gruntfuggly/todo-tree/wiki/Configuration-Examples).

**Comment by Gruntfuggly** [comment] 2020-10-25 15:33
I'm going to close this as the extension works as expected. Please feel free to reopen if necessary.

**Closed by Gruntfuggly** 2020-10-25 15:33 UTC
