### ISSUE TITLE
todo-tree.general.tags: Escaping Regex Characters

### ISSUE THREAD

**Issue by bohni** [Gruntfuggly/todo-tree#218] opened 2019-09-17 11:56 UTC
#85 : There are more regex chars than the backslash...

I'm writing documentation in asciidoc an I use a asiicoc variable {todo-item}

How can I add this to tags?
* "todo-item": there are no hits
* "{todo-item}": regex complains "error: repetition operator missing expression"
* "\\{todo-item\\}": Jsonc complains "invalid escape character in string"

Solution:
All regex characters should be escaped before building the regex search string

**Comment by Gruntfuggly** [comment] 2019-09-17 12:40
Probably your best bet in this case is to ignore the tags and just update the regex directly, e.g.
```
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*(($TAGS)|\\{todo-item\\})|^\\s*- \\[ \\])"
```
or if you want to keep it really simple
```
"todo-tree.regex.regex": "\\{todo-item\\}"
```
I'll see if it's possible to escape other characters...

**Comment by ailixter** [comment] 2019-09-24 14:23
it's a pity but it does not work for me.
\?\?\? breaks things (and \\?\\?\\? breaks all the same)

**Comment by Gruntfuggly** [comment] 2019-09-24 15:16
If you simplify the regex to `(\?\?\?)`, via the GUI, or `(\\?\\?\\?)` in the .json, does it find anything?

**Comment by ailixter** [comment] 2019-09-25 13:27
"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*($TAGS|\\?\\?\\?)|^\\s*-
\\[ \\])" – todo-tree: alternations cannot currently contain empty
sub-expressions
"todo-tree.regex.regex":
"((//|#|<!--|;|/\\*|^)\\s*(($TAGS)|\\?\\?\\?)|^\\s*- \\[ \\])" – works, but
does not fetch the tag ??? to show in treeview
it seems ($TAGS) is substituted, not $TAGS


вт, 24 сент. 2019 г. в 18:16, Nigel Scott <notifications@github.com>:

**Comment by Gruntfuggly** [comment] 2019-09-25 15:31
Yes, that's why I was suggesting updating the `todo-tree.regex.regex` directly, and remove `$TAGS`:
i.e.
`"todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*(\\?\\?\\?)|^\\s*- \\[ \\])"`
If you try that what happens?

**Comment by Gruntfuggly** [comment] 2019-09-25 15:33
The problem is caused by using regex's to find things in another regex... substituting the $TAGS works if the tags are simple, but putting regex characters in there makes it too complicated.

**Comment by ailixter** [comment] 2019-09-25 18:36
speaking frankly, I don't think so) it seems quite enough to escape tags (from "todo-tree.general.tags") properly and then just replace palceholder _literally_.
the problem is that escaping is probably not done while backslashes (inserted in tags in hope to do escaping manually) converted into 0x5c. check'n'mate)
nevertheless the extension is must have, thank you anyway)

**Comment by Gruntfuggly** [comment] 2019-09-25 21:54
It's not quite as simple as you might think because the regex has to be inserted into a string which is passed as a command to ripgrep. If you just insert the tags without the 0x5c the backslashes in the tags disappear unless they are double escaped.

For instance if you want to use a tag like `# TO\DO`, then the regex you need is
`#\\s*(TO\\\\\\DO)`

**Comment by am0d** [comment] 2019-09-26 14:07
I'd like to share my use case here as well.  I've modified the regex to search for Markdown checkboxes in various states, with the following regex: `((//|#|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*-\\s*(\\[.\\]))`.

This works, but I'd really like to use the markdown checkbox value as a tag, and I can't currently do that.

`"[?]"` would be a sample tag I'd like to use - there's 3 regex characters in there, so the TAGS search breaks with that.  However, if I change that tag to `"\[\?\]"` then it doesn't match because the tag lookup is a literal string lookup, so it doesn't apply regex escapes.

Perhaps the solution here is to allow the escapes in the tags, but then apply a regex match to the tag lookup also?

**Comment by bohni** [comment] 2019-09-26 18:54
utils.js, Line 125 should be

```
tags = tags.replace( /\[|\\|\^|\$|\.|\||\?|\*|\+|\(|\)|\{|\}/g, function(x) {
            return x.replace(x, '\\' + x);
        });
```
Explanation:
All meta characters for regular expressions are escaped with a backslash (see [Backslash escapes a metacharacter](https://www.regular-expressions.info/refcharacters.html))
The tag `TO\DO` thus becomes the regular expression `TO\\DO` and a `[TODO]` becomes `\[TODO]`.
Tags that have been excaped in this way should be found by a regex engine.
I couldn't test it in the extension because I don't know how to develop and test/debug extensons in VS Code.

**Comment by bohni** [comment] 2019-09-26 19:14
I searched the web and was able to test the extension ( --extensionDevelopmentPath= )

my {todo-item} is now shown in the tree

**Comment by Gruntfuggly** [comment] 2019-09-27 08:11
Unfortunately it only works for `{todo-item}`. As I said above, the backslashes are the problem because the command has to be passed to ripgrep. It also breaks if you have more that one tag defined because now the alternation character `|` is escaped (see line 485 https://travis-ci.com/Gruntfuggly/todo-tree/jobs/239517191).

At the moment, I think you will just need to modify the regex directly and escape the `{` as in my original reply.

Just to be clear, converting the tag `TO\DO` into `TO\\DO` isn't enough on it's own.

**Comment by Gruntfuggly** [comment] 2019-09-27 09:39
OK - I've made some further changes, and it seems to be working! 

Uploading a new version now - please let me know if it works.

**Comment by bohni** [comment] 2019-09-27 19:25
Thanks. Most Tags are now recognized.

I tested with multiple backslashes - i know, thats strange and far away from normal usage :-)

```
TODO: TODO 0
TO\DO: TO\DO 1
TO\\DO: TO\\DO 2
TO\\\DO: TO\\\DO 3
TO\\\\DO: TO\\\\DO 4
TO\\\\\DO: TO\\\\\DO 5
TO\\\\\\DO: TO\\\\\\DO 6
TO\\\\\\\DO: TO\\\\\\\DO 7
TO\\\\\\\\DO: TO\\\\\\\\DO 8
TO\\\\\\\\\DO: TO\\\\\\\\\DO 9
TO\\\\\\\\\\DO: TO\\\\\\\\\\DO 10
TO\\\\\\\\\\\DO: TO\\\\\\\\\\\DO 11
TO\\\\\\\\\\\\DO: TO\\\\\\\\\\\\DO 12
TO\\\\\\\\\\\\\DO: TO\\\\\\\\\\\\\DO 13
```

```
"todo-tree.general.tags": [
        "TODO",
        "TO\\DO",
        "TO\\\\DO",
        "TO\\\\\\DO",
        "TO\\\\\\\\DO",
        "TO\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\\\\\\\\\\\DO",
        "TO\\\\\\\\\\\\\\\\\\\\\\\\\\DO",
    ],
```

but strangely enough, not all tags are recognized:

![image](https://user-images.githubusercontent.com/1252254/65796407-cd624d80-e16c-11e9-9558-1a648bec6625.png)

From my point of view, this issue could be closed. Thanks again.

**Comment by Gruntfuggly** [comment] 2019-09-27 20:48
You'll need an even number of backslashes because an odd number will escape a backslash and then simply escape the next character. The crazy thing is for each backslash that is required in the regex, it has to put 6 in!

**Comment by tobiasdiez** [comment] 2020-07-29 11:03
I've trouble making escaping work in tags:
```
    "todo-tree.regex.regex": "($TAGS)",
    "todo-tree.general.tags": [
        "test",
        "\\Ctodo",
        "\\Dtodo"
    ],
```
it works, commands like `\Ctodo` are correctly recognized and highlighted. However, at the same time I get the following error:
```
todo-tree: regex parse error:
    (test|\\\Dtodo|\\\Ctodo)
                     ^^
error: unrecognized escape sequence
```
It seems that the backslash is twice escaped now.

**Comment by Gruntfuggly** [comment] 2020-07-29 11:31
Did you modify the settings through the GUI editor at one point? I think that is what causes the issue. If I do it directly through the .json file, it works OK for me without generating the error.

**Comment by Gruntfuggly** [comment] 2020-07-29 11:34
Although saying that, it led me to a bug which I think may remove the issue anyway.

**Comment by bcaddy** [comment] 2020-08-24 20:18
I'm also having this issue. I did originally try to update it through the GUI but have since then deleted those lines in `settings.json` 

```
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "todo",
        "\\Ctodo",
        "\\Dtodo"
    ],
    "todo-tree.regex.regex": "((//|#|\\*|<!--|;|/\\*|^)\\s*($TAGS)|^\\s*- \\[ \\])"
```

**Comment by Gruntfuggly** [comment] 2020-10-04 17:19
Hi - are you still having this issue?

**Comment by bcaddy** [comment] 2020-10-05 14:34
Yep, I'm trying to make the doxygen command `\todo` show up in todo-tree and nothing in this thread is working

**Comment by Gruntfuggly** [comment] 2020-10-07 09:12
If you add 'todo' (lowercase) as a tag and then set the regex to this:
`(\\)($TAGS)` in the GUI or
`"(\\\\)($TAGS)"` in the .json
it should work.

That's obviously the simplest regex you can have, but if you want to include `\todo` in the default regex, just add the first part as an option in the first bracketed section, e.g.
`((//|#|<!--|;|/\*|^|\\)\s*($TAGS)|^\s*- \[ \])` in the GUI or
`"((//|#|<!--|;|/\\*|^|\\\\)\\s*($TAGS)|^\\s*- \\[ \\])" in the .json.

**Comment by bcaddy** [comment] 2020-10-07 14:32
I took the first option and that did it. Thanks!

**Comment by bcaddy** [comment] 2020-10-13 13:38
Update, I am now getting the following error and it no longer find `TODO` just `\todo`

```
todo-tree: regex parse error: (\)(todo|XXX|TODO|HACK|FIXME|BUG) ^ error: unclosed group
```

**Comment by Gruntfuggly** [comment] 2020-10-13 13:40
Please can you post you configuration?

**Comment by bcaddy** [comment] 2020-10-13 13:41
This is all the todo-tree related stuff in my settings.json file. Is that what you need?
```
"todo-tree.tree.showScanModeButton": false,
    "todo-tree.general.tags": [
        "BUG",
        "HACK",
        "FIXME",
        "TODO",
        "XXX",
        "todo"
    ],
    "todo-tree.regex.regex": "(\\\\)($TAGS)",
```

**Comment by Gruntfuggly** [comment] 2020-10-13 13:50
Yes, something has broken in the latest version. Will look into it.

**Comment by Gruntfuggly** [comment] 2020-10-13 13:58
You can probably go back to the previous version in the short term.

**Comment by bcaddy** [comment] 2020-10-13 14:34
Sounds good, I'll just use \todo for now. I should probably be doing that anyway so Doxygen reports all the todos

**Comment by Gruntfuggly** [comment] 2020-10-29 11:59
I'm going to close this now because I think it works as expected in the latest version.

**Comment by bcaddy** [comment] 2020-10-29 13:28
It's working for me. Thanks!

**Closed** 2020-10-29 13:38 UTC
Labels: bug, enhancement, fixed

**Comment by rklasen** [comment] 2021-01-11 10:15
Hi, I think I'm encountering a similar issue. I'm on the most recent version of todo-tree, and I keep getting this error message:

![image](https://user-images.githubusercontent.com/13201731/104168297-2277b080-53fe-11eb-954c-a28658cdeac6.png)

I'm currently using mostly a custom LaTeX command `\todo{Text here}`. This is my current config: 

```
"todo-tree.tree.showScanModeButton": true,
  "todo-tree.general.tags": ["BUG", "HACK", "FIXME", "TODO", "todo"],
  "todo-tree.highlights.enabled": true,
  "todo-tree.filtering.includeGlobs": ["**/*.tex"],
  "todo-tree.regex.regex": "(\\)($TAGS)"
```

Best wishes!

**Comment by Gruntfuggly** [comment] 2021-01-11 10:30
You need to double escape the "\\", e.g.
` "todo-tree.regex.regex": "(\\\\)($TAGS)"`

It's a bit confusing because the GUI settings editor does it for you.

**Comment by rklasen** [comment] 2021-01-11 10:32
Thank you for the quick reply, that did it!
