### ISSUE TITLE
Not working on Macs...

### ISSUE THREAD

**Issue by jasonvogel** [Gruntfuggly/todo-tree#707] opened 2022-12-14 20:20 UTC
**Environment:** Visual Studio Code (Version: 1.74.0) on Mac (Monterey 12.6.1)

- The extension installed fine.  
- I restarted VSC, but the tree remains empty.  I tried both Python and C# files.

Any help or suggestions would be appreciated.

**Comment by Gruntfuggly** [comment] 2022-12-15 00:18
Please post an example of what you would expect it to find. It probably just needs the regex to be configured.

**Comment by jasonvogel** [comment] 2022-12-15 22:28
> Please post an example of what you would expect it to find. It probably just needs the regex to be configured.
> 
> It definitely works on Macs - that's what I developed it on. 8-)


In short, it's not rendering, _anything_.  It's installed and enabled, but not finding/showing any ToDo's.  Is there a log or something that I can look at for errors?

**Comment by Gruntfuggly** [comment] 2022-12-16 19:57
The default tags it will match are BUG, HACK, FIXME, TODO, XXX, [ ] and [x]

So to match the tags in your screenshot, you can set `"todo-tree.regex.regexCaseSensitive": false` or modify the list of tags using the command **Todo Tree: Add Tag** and add `ToDo` and `FixMe`, etc.

**Comment by Gruntfuggly** [comment] 2023-01-22 15:14
Closing due to lack of updates. Please feel free to re-open if you still believe there is an issue.

**Closed by Gruntfuggly** 2023-01-22 15:14 UTC

**Comment by xieshuaix** [comment] 2023-01-29 02:04
I am having similar problem. Could you help check what might be the issue? Thanks.
![image](https://user-images.githubusercontent.com/22043680/215300109-e4bb88ec-32bf-46f1-978d-d15952955ab3.png)

![image](https://user-images.githubusercontent.com/22043680/215300145-84a5acc5-5a98-4301-8403-c511391b1e8e.png)

I found that this setting: "Filtering: Use Built In Excludes"  might be the cause of this issue. When set to none, file excludes, the extention works fine. But when excluding serach results (see search exclude glob patterns below, nothing unusual, searching files with TODO works), the extenstion stops workinng.
![image](https://user-images.githubusercontent.com/22043680/215300317-2f3a2626-583f-45bd-b4b0-7b74b6bfc7b0.png)

**Comment by Gruntfuggly** [comment] 2023-01-30 10:07
Have you tried modifying the list of excludes to work out which one causes it to stop finding anything? Without knowing your folder structure or filenames I can't really help.
