### ISSUE TITLE
Icons not showing on insider build

### ISSUE THREAD

**Issue by rickstaa** [Gruntfuggly/todo-tree#435] opened 2021-02-15 09:02 UTC
The icons seem to be broken in the newest insider build (1.54.0-insider). This problem is not present in the regular build (1.53.2).

## Current behaviour
![image](https://user-images.githubusercontent.com/17570430/107925665-06bf7700-6f75-11eb-9430-98f6b31d77ce.png)

## Expected behaviour

![image](https://user-images.githubusercontent.com/17570430/107925643-0030ff80-6f75-11eb-969d-cee9f180f817.png)

## What I already tried
* Reinstalling the extension
* Reinstalling vscode
* Resetting the extension settings.

## System information

**Version**: 1.54.0-insider
**Commit**: a699ffaee62010c4634d301da2bbdb7646b8d1da
**Date**: 2021-02-15T05:17:46.733Z
**Electron**: 11.2.3
**Chrome**: 87.0.4280.141
**Node.js**: 12.18.3
**V8**: 8.7.220.31-electron.0
**OS**: Linux x64 5.8.0-43-generic
**Extension version**: v0.0.196

## Log

![image](https://user-images.githubusercontent.com/17570430/107925991-733a7600-6f75-11eb-84fc-608133616772.png)

**Comment by Gruntfuggly** [comment] 2021-02-15 09:17
Yes, I can confirm they're not appearing. Neither .svg icons, octicons or codicons are working, so I presume something has changed in the tree rendering. 

Will investigate.

**Comment by rickstaa** [comment] 2021-02-15 09:23
@Gruntfuggly Great thanks a lot! Let me know if you need additional info.

**Comment by Gruntfuggly** [comment] 2021-02-15 22:47
codicons are working, but not octicons or svgs. These are both accessed using globalStoragePath which looks like it has been deprecated. I'm guessing insiders may have removed support or changed it some other way.

I'll update to the new globalStorageUri and see if that fixes it.

**Comment by Gruntfuggly** [comment] 2021-02-15 23:35
Hmmm. It seems to not like pointing the icon path to files stored outside the extension folder. I've raised an issue: https://github.com/microsoft/vscode/issues/116735

**Comment by Gruntfuggly** [comment] 2021-02-23 09:25
Fixed in the latest insiders.

**Closed by Gruntfuggly** 2021-02-23 09:25 UTC
