### ISSUE TITLE
Bad grouping in multi-root workspace

### ISSUE THREAD

**Issue by AlekSi** [Gruntfuggly/todo-tree#100] opened 2018-11-29 09:05 UTC
I have 4 roots: pmm-admin, pmm, pmm-agent, pmm-managed. But todo-tree grouped them incorrectly (note the `..`).
![image](https://user-images.githubusercontent.com/11512/49210778-04da5f00-f3cf-11e8-89a3-4bf0ac2f32b7.png)
I think the solution there is to never allow `..`.

**Comment by Gruntfuggly** [comment] 2018-11-29 09:08
I'm not sure how it's managed to find '..' as a folder in the path - it should use absolute paths for everything in the tree.

Could you post the contents of the todo-tree output view please?

**Comment by AlekSi** [comment] 2018-11-30 12:39
https://gist.githubusercontent.com/AlekSi/75a07b7375fe7bf1851c672cc71f0768/raw/f569714a5b47ecb41a4067752cf6c2153883fe0a/gistfile1.txt

**Comment by Gruntfuggly** [comment] 2018-12-08 17:21
I can't reproduce this - If I populate the tree with the matches from your output, it behaves as expected.

Can you tell me if this happens when you close all the files in the window and reload?

If you don't mind, could you also do some remote debugging for me? Assuming you have the latest version of the extension, can you add the following to `.vscode/extensions/gruntfuggly.todo-tree-0.0.107/tree.js` at line 498:
```
            if( relativePath !== "" )
            {
                pathElements = relativePath.split( path.sep );
                if( pathElements.length > 0 && pathElements[ 0 ] === ".." )
                {
                    console.log( "rn:" + rootNode.fsPath );
                    console.log( "tn:" + result.file );
                }
            }
```

Let me know what is shown in the developer console (Help -> Toggle Developer Tools).

**Comment by Gruntfuggly** [comment] 2019-01-29 18:33
Hi - did you get a chance to try this out?

**Comment by AlekSi** [comment] 2019-01-30 10:38
Hi. I reinstalled OS in December and no longer can reproduce that issue. 😄

**Comment by Gruntfuggly** [comment] 2019-01-30 17:49
OK - hopefully it was fixed by an intermediate update. 

I'll file it under "Move along, nothing to see here..."

**Comment by canemacchina** [comment] 2020-01-09 13:38
@Gruntfuggly  same problem here, with the latest version. I've added your debug code, the result il very long as I have many project opened, so I copy just one of the output. I hope is enough. If you want I can do more tests for you.

```js
[Extension Host] rn:/Users/l6/git/viralize/viralize
[Extension Host] tn:/Users/l6/git/viralize/viralize-injector/src/formats/banner.js
```

**Comment by Gruntfuggly** [comment] 2020-01-21 09:17
Are you seeing '..' nodes in the tree?

**Comment by canemacchina** [comment] 2020-01-21 12:05
Yes, I see `..` in the tree. Here it is a screenshot:
![Screenshot 2020-01-21 at 13 02 10](https://user-images.githubusercontent.com/5285750/72803445-68b48c80-3c4e-11ea-851f-4f5d06921182.png)

Is not exactly that a path starts with another. They have similar names but are different folders.

`/Users/l6/git/viralize/viralize` is a folder with a project
`/Users/l6/git/viralize/viralize-injector` is another folder with a project
`/Users/l6/git/viralize/viralize-player` is yet another folder with a project

**Comment by Gruntfuggly** [comment] 2020-01-21 13:19
I think I'll need more of the debug log. If it's not sensitive, would you be able to attach it all to this issue? That way I can recreate the search results without needing your workspace.

**Comment by canemacchina** [comment] 2020-01-21 16:40
Are you talking about the log on the console tab of the developer tools? I don't think is a problem to attach here my log, but is quite long... Do you need something particular?

**Comment by Gruntfuggly** [comment] 2020-01-21 16:46
No, the debug log from the "Todo Tree" Output view. You might need to enable `todo-tree.general.debug`. It should contain all the search results.

**Comment by canemacchina** [comment] 2020-01-21 21:47
Have you released something new? The error is changed. Now some project are disappeared from the todos view and an error occurs:

```
TypeError: Cannot read property 'trim' of undefined
	at createTodoNode (/Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/tree.js:166)
	at TreeNodeProvider.add (/Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/tree.js:609)
	at /Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/extension.js:105
	at Array.map (<anonymous>)
	at addResultsToTree (/Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/extension.js:101)
	at /Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/extension.js:371
	at onComplete (/Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/extension.js:207)
	at /Users/l6/.vscode/extensions/gruntfuggly.todo-tree-0.0.165/extension.js:237
$onExtensionRuntimeError @ mainThreadExtensionService.ts:66
```

This is the new situation: 
![Screenshot 2020-01-21 at 22 46 03](https://user-images.githubusercontent.com/5285750/72845891-d210bb80-3c9f-11ea-91a6-9dd3888cbc46.png)

About the log. I can send it to you but I have to strip TODO message. It's not a problem, right?
This is the entire log (sorry is quite big):

```
Searching /Users/l6/git/viralize/viralize-adserver-experiments...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO:
/Users/l6/git/viralize/viralize-adserver-experiments/vendors/viralize-common/tests/schemas/__init__.py:36:13:            # TODO:

 Match (File): {"file":"/Users/l6/git/viralize/viralize-adserver-experiments/vendors/viralize-common/tests/schemas/__init__.py","line":"36","column":"13","match":"            # TODO:
Searching /Users/l6/git/viralize/viralize-pagetests...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO:
/Users/l6/git/viralize/viralize-pagetests/bootstrap/css/bootstrap.css.map:1:187635:[Omitted long line with 1 matches]

/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/elle/cm/elle/styles/global.2014-03-31.css:1642:1:/* TODO:
/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/spaziogames/www.spaziogames.it/includes/1/js/general.js:1003:13:            // TODO:
/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/spaziogames/www.spaziogames.it/includes/1/js/general.js:1058:21:                    // TODO:
/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/spaziogames/www.spaziogames.it/includes/1/js/general.js:1442:17:                // TODO:
/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/edreams/www.edreams.it/engine/static-content/bb1677883319cdf5/js/eDreams-min2.js:4203:47:        var roomDivB = $('#hRoom' + i + 'B'); // TODO:

/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/gazzetta/js2.gazzettaobjects.it/includes2013/LIBS/js/vendor/plugins/jquery.validate-v=20140207160154.js:1111:4:			// TODO:

 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/bootstrap/css/bootstrap.css.map","line":"1","column":"187635","match":"[Omitted long line with 1 matches]"}
 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/elle/cm/elle/styles/global.2014-03-31.css","line":"1642","column":"1","match":"/* TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/spaziogames/www.spaziogames.it/includes/1/js/general.js","line":"1003","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/spaziogames/www.spaziogames.it/includes/1/js/general.js","line":"1058","column":"21","match":"                    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/spaziogames/www.spaziogames.it/includes/1/js/general.js","line":"1442","column":"17","match":"                // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/edreams/www.edreams.it/engine/static-content/bb1677883319cdf5/js/eDreams-min2.js","line":"4203","column":"47","match":"        var roomDivB = $('#hRoom' + i + 'B'); // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-pagetests/pub_fake_pages/gazzetta/js2.gazzettaobjects.it/includes2013/LIBS/js/vendor/plugins/jquery.validate-v=20140207160154.js","line":"1111","column":"4","match":"\t\t\t// TODO:
Searching /Users/l6/git/viralize/viralize-common...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO:
/Users/l6/git/viralize/viralize-common/tests/schemas/__init__.py:36:13:            # TODO:

 Match (File): {"file":"/Users/l6/git/viralize/viralize-common/tests/schemas/__init__.py","line":"36","column":"13","match":"            # TODO:
Searching /Users/l6/git/viralize/viralize...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO:
/Users/l6/git/viralize/viralize/viralize/web/impression.py:226:9:        # TODO:
/Users/l6/git/viralize/viralize/viralize/env/__init__.py:186:9:        # TODO:

/Users/l6/git/viralize/viralize/viralize/web/player_conf/video.py:234:9:        # TODO:
/Users/l6/git/viralize/viralize/viralize/web/req_env/base.py:104:9:        # TODO:

/Users/l6/git/viralize/viralize/viralize/storage/contents_cache/build.py:291:17:                # TODO:
/Users/l6/git/viralize/viralize/tests/handlers/cookie/test_user_dnt.py:51:9:        # TODO:
/Users/l6/git/viralize/viralize/viralize/web/handlers/debug/content_selection.py:97:17:                # TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:741:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:891:5:    // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:1233:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:1732:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:1748:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:2140:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:2155:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js:2245:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/native.js:2568:34:        this.minElementArea = 1; // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/native.js:4659:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/display.js:2592:34:        this.minElementArea = 1; // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/display.js:4602:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid.js:2328:34:        this.minElementArea = 1; // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid.js:4555:5:    // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/strip.js:2644:34:        this.minElementArea = 1; // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/strip.js:4609:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/banner.js:2322:34:        this.minElementArea = 1; // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/banner.js:4307:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/banner.js:4310:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/outstream.js:2690:34:        this.minElementArea = 1; // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/injectors/outstream.js:4728:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:1693:13:            // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:1714:13:            // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:3057:76:					result.push('&', esc(orderedLabelName), '=', esc(orderedLabelValue)); // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:3067:67:						result.push('&', esc(name), '=', esc(tempLabelsMap[name])); // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:3232:1:// TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:6726:7:      // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:6766:31:      if(n < s.length + 11) { // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:6948:7:      // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js:10122:13:            // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player_banner.js:3863:9:        // TODO:

/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:529:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:679:5:    // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:1021:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:6942:21:                    // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:8962:13:            // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:13267:17:                // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:13565:9:        // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js:14817:13:            // TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/vendor/jquery.js:810:8:							// TODO:
/Users/l6/git/viralize/viralize/viralize/web/static/player/vendor/jquery.js:824:7:						// TODO:

 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/impression.py","line":"226","column":"9","match":"        # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/env/__init__.py","line":"186","column":"9","match":"        # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/player_conf/video.py","line":"234","column":"9","match":"        # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/req_env/base.py","line":"104","column":"9","match":"        # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/storage/contents_cache/build.py","line":"291","column":"17","match":"                # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/tests/handlers/cookie/test_user_dnt.py","line":"51","column":"9","match":"        # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/handlers/debug/content_selection.py","line":"97","column":"17","match":"                # TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"741","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"891","column":"5","match":"    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"1233","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"1732","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"1748","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"2140","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"2155","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid_standalone.js","line":"2245","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/native.js","line":"2568","column":"34","match":"        this.minElementArea = 1; // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/native.js","line":"4659","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/display.js","line":"2592","column":"34","match":"        this.minElementArea = 1; // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/display.js","line":"4602","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid.js","line":"2328","column":"34","match":"        this.minElementArea = 1; // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/vpaid.js","line":"4555","column":"5","match":"    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/strip.js","line":"2644","column":"34","match":"        this.minElementArea = 1; // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/strip.js","line":"4609","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/banner.js","line":"2322","column":"34","match":"        this.minElementArea = 1; // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/banner.js","line":"4307","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/banner.js","line":"4310","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/outstream.js","line":"2690","column":"34","match":"        this.minElementArea = 1; // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/injectors/outstream.js","line":"4728","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"1693","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"1714","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"3057","column":"76","match":"\t\t\t\t\tresult.push('&', esc(orderedLabelName), '=', esc(orderedLabelValue)); // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"3067","column":"67","match":"\t\t\t\t\t\tresult.push('&', esc(name), '=', esc(tempLabelsMap[name])); // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"3232","column":"1","match":"// TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"6726","column":"7","match":"      // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"6766","column":"31","match":"      if(n < s.length + 11) { // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"6948","column":"7","match":"      // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/vendor/comScore-JS-6.3.4.190424.js","line":"10122","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player_banner.js","line":"3863","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"529","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"679","column":"5","match":"    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"1021","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"6942","column":"21","match":"                    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"8962","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"13267","column":"17","match":"                // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"13565","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/viralize/viralize_player.js","line":"14817","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/vendor/jquery.js","line":"810","column":"8","match":"\t\t\t\t\t\t\t// TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize/viralize/web/static/player/vendor/jquery.js","line":"824","column":"7","match":"\t\t\t\t\t\t// TODO:
Searching /Users/l6/git/viralize/viralize-player...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO:
/Users/l6/git/viralize/viralize-player/src_mobi/js/mobi/mobi-vast.js:279:9:        // TODO:
/Users/l6/git/viralize/viralize-player/src_mobi/js/lib/vastbuilder.js:158:21:                    // TODO:
/Users/l6/git/viralize/viralize-player/src/js/lib/adSkin.js:114:13:            // TODO:
/Users/l6/git/viralize/viralize-player/src/js/lib/vastbuilder.js:158:21:                    // TODO:
/Users/l6/git/viralize/viralize-player/src/js/controllers/contents.js:389:13:            // TODO:
/Users/l6/git/viralize/viralize-player/src/js/banner/controller.js:675:9:        // TODO:

/Users/l6/git/viralize/viralize-player/src/js/lib/ads/loaders/adsLoaderIMA.js:129:17:                // TODO:
/Users/l6/git/viralize/viralize-player/src/js/lib/ads/loaders/adsLoaderIMA.js:427:9:        // TODO:

 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src_mobi/js/mobi/mobi-vast.js","line":"279","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src_mobi/js/lib/vastbuilder.js","line":"158","column":"21","match":"                    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src/js/lib/adSkin.js","line":"114","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src/js/lib/vastbuilder.js","line":"158","column":"21","match":"                    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src/js/controllers/contents.js","line":"389","column":"13","match":"            // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src/js/banner/controller.js","line":"675","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src/js/lib/ads/loaders/adsLoaderIMA.js","line":"129","column":"17","match":"                // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-player/src/js/lib/ads/loaders/adsLoaderIMA.js","line":"427","column":"9","match":"        // TODO:
Searching /Users/l6/git/viralize/viralize-injector...
Command: /Applications/Visual\ Studio\ Code.app/Contents/Resources/app/node_modules.asar.unpacked/vscode-ripgrep/bin/rg --no-messages --vimgrep -H --column --line-number --color never --max-columns=1000 --no-config  -e "((//|#|<!--|;|/\*|^)\s*(TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/native.js:100:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/display.js:106:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/vpaidBase.js:413:5:    // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/strip.js:61:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/outstream.js:47:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/banner.js:81:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/banner.js:84:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VpaidPlayer.js:66:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VpaidPlayer.js:82:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VastPlayer.js:66:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VastPlayer.js:81:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VastPlayer.js:171:9:        // TODO:
/Users/l6/git/viralize/viralize-injector/src/lib/viewability/impl/standardViewability.js:41:34:        this.minElementArea = 1; // TODO:

 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/native.js","line":"100","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/display.js","line":"106","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/vpaidBase.js","line":"413","column":"5","match":"    // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/strip.js","line":"61","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/outstream.js","line":"47","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/banner.js","line":"81","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/banner.js","line":"84","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VpaidPlayer.js","line":"66","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VpaidPlayer.js","line":"82","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VastPlayer.js","line":"66","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VastPlayer.js","line":"81","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/formats/vpaid_standalone/VastPlayer.js","line":"171","column":"9","match":"        // TODO:
 Match (File): {"file":"/Users/l6/git/viralize/viralize-injector/src/lib/viewability/impl/standardViewability.js","line":"41","column":"34","match":"        this.minElementArea = 1; // TODO:
Found 78 items
Found 78 items
```

**Comment by canemacchina** [comment] 2020-01-23 09:37
update: the `TypeError: Cannot read property 'trim' of undefined` seem random, isn't fired every time. Based on if the error occurs or not, TODO-TREE shows different things

**Comment by Gruntfuggly** [comment] 2020-01-23 13:17
Are you still seeing the error with version 0.0.166? I uploaded a new version last night which should have fixed the trim error. If that's the case I'll try to work out whats going on with your tree.

**Comment by canemacchina** [comment] 2020-01-23 15:12
No, the problem with trim seems fixed. The other remains (the one of this issue).
Thanks!

**Comment by Gruntfuggly** [comment] 2020-01-29 21:05
OK - I can sort of recreate the original problem if I use your search results. 

Can you confirm - what is the folder of the workspace itself?

Also, can you send me your todo-tree config settings too so I can make sure the tree is the same as what you should be seeing.

**Comment by canemacchina** [comment] 2020-01-30 08:58
My todo tree config is the following:

```
"todo-tree.highlights.customHighlight": {
    "TODO": {
        "foreground": "#ffcc00",
        "iconColour": "#ffcc00",
        "icon": "check"
    },
    "FIXME": {
        "foreground": "#cc4646",
        "iconColour": "#cc4646",
        "icon": "issue-opened"
    }
},
"todo-tree.highlights.defaultHighlight": {
    "type": "tag"
},
"todo-tree.tree.flat": true,
"todo-tree.tree.grouped": true,
"todo-tree.highlights.highlightDelay": 0,
"todo-tree.tree.showCountsInTree": true,
"todo-tree.tree.showInExplorer": false
```

Sorry, I don't well understand the question about my workspace. Are you asking me which is the main folder of the workspace? There's no one, is a multi project workspace where I have loaded six different project. Every project have its own directory (obviously), although the have a common path.

This is my workspace:

```
{
	"folders": [
		{
			"name": "INJECTOR",
			"path": "/Users/l6/git/viralize/viralize-injector"
		},
		{
			"name": "PLAYER",
			"path": "/Users/l6/git/viralize/viralize-player"
		},
		{
			"name": "ADSERVER",
			"path": "/Users/l6/git/viralize/viralize"
		},
		{
			"name": "COMMON",
			"path": "/Users/l6/git/viralize/viralize-common"
		},
		{
			"name": "EXPERIMENTS",
			"path": "/Users/l6/git/viralize/viralize-adserver-experiments"
		},
		{
			"name": "PAGETESTS",
			"path": "/Users/l6/git/viralize/viralize-pagetests"
		}
	],
	"settings": {}
}
```

**Comment by Gruntfuggly** [comment] 2020-01-30 09:56
OK - that's great thank you. The workspace settings answers my question. :grin:

**Comment by canemacchina** [comment] 2020-01-30 11:19
I suppose so, but I wasn't 100% sure 😅

**Comment by Gruntfuggly** [comment] 2020-01-30 20:21
OK - got it. It was an over-simple check for paths starting with other paths. It will be fixed in the next release.

**Comment by Gruntfuggly** [comment] 2020-01-30 20:39
Please try the latest version and let me know if it works.

**Comment by canemacchina** [comment] 2020-01-31 08:51
Yes, it works! 
Many thanks!

**Closed** 2020-02-14 09:08 UTC
Labels: bug, fixed
