### ISSUE TITLE
Amount badge [suggestion]

### ISSUE THREAD

**Issue by SergioTx** [Gruntfuggly/todo-tree#22] opened 2018-05-15 11:20 UTC
Please, add a badge showing how many TODOs left are there. Just like version control has.

![image](https://user-images.githubusercontent.com/22587994/40053697-997c15dc-5842-11e8-87b0-444531094fa1.png)

It might need to have a toggle button as it might be annoying for some people.

**Comment by Gruntfuggly** [comment] 2018-05-15 11:26
I would love to, but unfortunately there is no API to do this yet. I'm sure it will added soon - I will add it as soon as it does.

**Comment by SergioTx** [comment] 2018-05-15 11:31
Oh, ok. Thank you.

Your extension is really useful 👍

**Comment by Gruntfuggly** [comment] 2018-05-15 11:40
Thanks - I'm pleased other people are finding it useful too. 8-)

**Comment by elf-pavlik** [comment] 2018-11-07 23:22
> I would love to, but unfortunately there is no API to do this yet. I'm sure it will added soon - I will add it as soon as it does.

Does vscode have an open issue for that? I'd like to upvote it :+1:

**Comment by Gruntfuggly** [comment] 2018-11-08 09:14
I don't think there is. The problem is that there is no obvious place to put the API - view containers are set up in the package.json rather than created in the extension code, which means there is no way to say something like `view.setCounter( 3 )`. 

View containers can only really container treeViews at the moment, so it could be an extension to `TreeView<T>`, but that doesn't totally make sense because the treeView could be in the explorer pane, or the activity bar could also be hidden, so you would not see it.

If you want to open an issue, I'll definitely support it though.

**Comment by elf-pavlik** [comment] 2018-11-08 13:44
I've just created issue for it https://github.com/Microsoft/vscode/issues/62783

**Comment by Gliptal** [comment] 2018-11-13 11:53
@elf-pavlik nice, thank you.

**Comment by Kenobi-the-2nd** [comment] 2020-02-18 19:29
I agree. This is a feature I would find helpful.

**Comment by metasean** [comment] 2020-10-06 22:12
I feel like I'm missing something obvious.  In particular, I know of several activity bar icons that can have a number badge over them, including:
- Explorer - unsaved files count
- Extensions - outdated extensions count
- SCM - pending changes count
- and others, for example, in this section's screenshot, the number 5 over the icon of a pair of humanoid shapes - https://code.visualstudio.com/api/references/contribution-points#product-icon-theme-example  (I have no idea what that humanoid shape icon represents, and it doesn't seem to align with anything I currently have in my VS Code UI.)

For styling purposes, I know this is identified as the `activityBarBadge`, but I'm definitely not seeing API documentation for setting its count for an extension.  However, digging through some code, [I think this is where the outdated extensions count is calculated](https://github.com/microsoft/vscode/blob/cced925ba1328bebd52f72d435e574efe786eba7/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts#L726-L734).  If I'm reading it correctly, that means that there's a generic [NumberBadge](https://github.com/microsoft/vscode/blob/cced925ba1328bebd52f72d435e574efe786eba7/src/vs/workbench/contrib/extensions/browser/extensionsViewlet.ts#L34) defined in [src/vs/workbench/services/activity/common/activity.ts#L57-L68](https://github.com/microsoft/vscode/blob/cced925ba1/src/vs/workbench/services/activity/common/activity.ts#L57-L68).

So is it possible that the functionality is already there, it's just not documented?  Or are y'all talking about something else altogether different?

**Comment by Gruntfuggly** [comment] 2020-10-07 11:01
Hi - the activity bar icons which have number badges are all built in vscode views. The extension API doesn't provide anything to set number badges on extension provided views.

There is definitely code in the application to show badges, but extensions have no access to it. If it was available I would definitely support it. :grin:

The image you've linked to is an example showing product icons, which as far a I know is a way to customise vscode to look like a new application, which is why the activity bar icons, the twistys, etc. are all different. I assume that the human icon is just a customised icon for one of the existing views.

**Comment by Gruntfuggly** [comment] 2021-01-21 13:30
I'm not sure the VSCode team are ever going to provide this functionality. In the mean time, I've made a change which shows the number of TODOs in the title of the view.

I'm going to close this, but if (when) the API does allow for badges, I'll implement it straight away.

**Closed by Gruntfuggly** 2021-01-21 13:30 UTC
Labels: enhancement, missing-api

**Comment by kanlukasz** [comment] 2022-03-30 12:39
It is possible that it will be in the API at any moment - https://github.com/microsoft/vscode/commit/a72732951698dd4e85b4b75f11f4886e845ffd17

**Comment by kanlukasz** [comment] 2022-09-01 09:25
We have it!
https://github.com/microsoft/vscode/issues/62783#event-7303294815
