### ISSUE TITLE
EINVAL: Invalid argument, mkdir

### ISSUE THREAD

**Issue by alavaros** [Gruntfuggly/todo-tree#441] opened 2021-02-25 09:16 UTC
## Issue:
The latest version of the extension is not working properly. This is the error message in VSCode:
```
EINVAL: Invalid argument, mkdir
'/C:/Users/my.user/AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo.tree'
```

## Versions:
**VSCode**:
```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042
```
**Todo Tree**: `v0.0.197`

## Note:
The previous version, `v0.0.196`, does work correctly.

**Comment by Gruntfuggly** [comment] 2021-02-25 09:18
Duplicate of #440. I'm working on it. 🙂

**Closed by Gruntfuggly** 2021-02-25 09:18 UTC

**Comment by alavaros** [comment] 2021-02-25 09:59
> Duplicate of #440. I'm working on it. 🙂

Sorry, I looked for it before opening the issue, but I couldn't find it.

Thanks.

**Comment by Gruntfuggly** [comment] 2021-02-25 10:00
No worries
