### ISSUE TITLE
Error on getting TODO list

### ISSUE THREAD

**Issue by Pabriuz** [Gruntfuggly/todo-tree#443] opened 2021-02-25 13:58 UTC
Gives error EINVAL: invalid argument, mkdir AppData/Roaming/Code/User/globalStorage/gruntfuggly.todo-tree

**Comment by Gruntfuggly** [comment] 2021-02-25 14:04
Duplicate of #440. I'm working on it. 🙂

**Closed** 2021-02-25 14:17 UTC
