### ISSUE TITLE
"ListError [CustomView] Invalid index -1" when trying to go to search results

### ISSUE THREAD

**Issue by AnrDaemon** [Gruntfuggly/todo-tree#237] opened 2019-10-21 18:07 UTC
When you search in TODOS panel, and hit `Enter` to go to the first search match, it spews "index out of bounds" when the matched TODO is still collapsed.

Oh, also, it does not properly set/reset filtering state on launch, and do not enable search-filter by default. Quite annoying.

**Comment by AnrDaemon** [comment] 2019-10-22 07:30
Builtin search of course. It's more than sufficient.

**Comment by Gruntfuggly** [comment] 2019-10-22 07:50
The built in search can't search collapsed tree nodes by design (see https://github.com/microsoft/vscode/issues/66811), which is why I left the filtering function in the extension.

However, I don't see the error you are seeing. Can you give me any more details? Or a screenshot or the output from the console.log?

Also, there is no way for the extension to know about the search-filter state, so it can't be set on launch unfortunately. Again, the extension filter is stored and retained though.

You could raise a vscode issue regarding storing the built in filter state between sessions.

**Comment by AnrDaemon** [comment] 2019-10-22 10:00
> The built in search can't search collapsed tree nodes by design

Doesn't looks to be true.
To me, it's finding them just fine, but does not expand the search results.

Reproduction case is rather simple.
 - Have extension panel activated in settings;
 - Create a 2-3 levels deep directory nesting;
 - Create a file with recognized tag;
 - Go to extension panel and collapse all nodes.
 - Type your search term.
 - Hit Enter.

**Comment by Gruntfuggly** [comment] 2019-10-22 12:08
What version of Code are you using? If I try your steps, it just says "Nothing found" as I would expect.

![image](https://user-images.githubusercontent.com/376658/67283966-94e43400-f4cc-11e9-945c-64f5580a52a3.png)
![image](https://user-images.githubusercontent.com/376658/67284024-b2190280-f4cc-11e9-93d9-7c3c9229c192.png)
![image](https://user-images.githubusercontent.com/376658/67284081-cc52e080-f4cc-11e9-83d6-06a9df94eb9b.png)

**Comment by Gruntfuggly** [comment] 2019-10-25 10:08
Hi - can you tell me what version of Code you are experiencing this problem with?

**Comment by AnrDaemon** [comment] 2019-10-25 11:33
```
Version: 1.39.2 (system setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601
```

```json
{
    "telemetry.enableTelemetry": false,
    "extensions.autoUpdate": false,
    "workbench.sideBar.location": "right",
    "editor.renderControlCharacters": false,
    "editor.fontSize": 13,
    "editor.lineHeight": 20,
    "window.zoomLevel": 1,
    "workbench.startupEditor": "newUntitledFile",
    "php.suggest.basic": false,
    "diffEditor.ignoreTrimWhitespace": false,
    "svn.sourceControl.countUnversioned": false,
    "git.path": "C:\\Cygwin64\\bin\\git.exe",
    "php.validate.executablePath": "C:\\Programs\\PHP\\bin\\php.exe",
    "files.trimTrailingWhitespace": true,
    "todohighlight.defaultStyle": {
        "color": "#dfdf00",
        "backgroundColor": "#7f0000"
    },
    "terminal.integrated.env.windows": {"PROMPT": "$P$_$G$S"},
    "todohighlight.include": [
        "**/*.js",
        "**/*.jsx",
        "**/*.ts",
        "**/*.tsx",
        "**/*.html",
        "**/*.php",
        "**/*.css",
        "**/*.scss",
        "**/*.smarty",
        "**/*.sql"
    ],
    "todohighlight.keywordsPattern": "(@?\\b(?:TODO|BUG|FIX(?:ME)?))\\b[^*\\r\\n]*|!!",
    "window.titleBarStyle": "native",
    "workbench.editor.highlightModifiedTabs": true,
    "files.hotExit": "off",
    "files.insertFinalNewline": true,
    "search.useGlobalIgnoreFiles": true,
    "scm.alwaysShowProviders": true,
    "editor.cursorWidth": 3,
    "editor.minimap.renderCharacters": false,
    "debug.internalConsoleOptions": "neverOpen",
    "terminal.integrated.shell.windows": "C:\\Cygwin64\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": ["-i"],
    "shellLauncher.shells.windows": [
        {
            "shell": "C:\\Cygwin64\\bin\\bash.exe",
            "label": "bash",
            "args": ["-i"]
        },
        {
            "shell": "C:\\Windows\\System32\\cmd.exe",
            "label": "CMD",
            "args": ["/Q", "/U", "/E:ON", "/V:ON", "/K"]
        },
        {
          "shell": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
          "label": "PowerShell"
        }
    ],
    "editor.renderWhitespace": "none",
    "files.trimFinalNewlines": true,
    "todo.embedded.provider": "ag",
    "todo.embedded.view.wholeLine": true,
    "editor.detectIndentation": false,
    "editor.wrappingIndent": "indent",
    "intelephense.files.maxSize": 4194304,
    "editor.acceptSuggestionOnEnter": "off",
    "editor.fontFamily": "'DejaVu Sans Mono', Consolas, 'Courier New', monospace",
    "editor.letterSpacing": 0.9,
    "todo-tree.filtering.passGlobsToRipgrep": false,
    "x-todo-tree.general.tags": [
        "BUG", "FIX", "FIXME", "TODO"
    ],
    "todo-tree.tree.showInExplorer": false,
    "todo-tree.tree.hideTreeWhenEmpty": false,
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|^)\\s*@?($TAGS)|^\\s*- \\[ \\])",
    "todo-tree.highlights.defaultHighlight": {
        "foreground": "#dfdf00",
        "background": "#ff0000",
        "opacity": 30,
        "borderRadius": 4,
        "type": "text",
        "rulerLane": "left",
        "iconColour": "blue"
    },
    "todo-tree.highlights.customHighlight": {
        "FIXME": {
            "iconColour": "red",
            "icon": "alert"
        },
        "BUG": {
            "iconColour": "green",
            "icon": "bug"
        }
    },
    "editor.find.seedSearchStringFromSelection": false
}
```

**Comment by AnrDaemon** [comment] 2019-10-25 11:36
I just rechecked now (since I've updated VS Code after initial report), and now it is indeed not finding anything (the tree panel is now completely empty when you search), but still produce mentioned error when you hit Enter (which makes more sense, now).
If you can catch this error message, it would be great, if not, this is a bug for VS Code core.

**Comment by AnrDaemon** [comment] 2019-10-25 11:53
Little followup correction.
If you unfold file to let it index, and fold again, bult-in filter will appear to work.

**Comment by Gruntfuggly** [comment] 2019-10-25 14:25
Where do you see the error? Is it a popup or in the console.log? Please could you attach a screenshot of the error?

**Comment by AnrDaemon** [comment] 2019-10-25 17:29
It's a popup. Will try to make a video, once I have a moment to run the dev. env at home.

**Comment by Gruntfuggly** [comment] 2019-12-02 13:37
Hi - did you have a chance to capture the popup?

**Comment by AnrDaemon** [comment] 2019-12-29 12:36
I have a working theory.
When I enter search term directly into the panel, the panel is filtered according to entered search term. Meaning, it gets empty.
If I then hit `<Enter>` key on that empty panel, it is probably trying to activate first selected item. Of an empty panel. Here we go, list index out of bounds.
Which means, this MAY be a bug in VS Code itself. Can you please check it?

**Comment by Gruntfuggly** [comment] 2020-01-26 14:07
Yes, this does look like a bug in vscode - filtering a custom view and pressing enter generates the popup you're seeing.

Interestingly if you try it on the standard explorer view, it tries to show the first thing it would have found in a search, even though it doesn't match the filter.

I'll raise a vscode issue.

**Comment by Gruntfuggly** [comment] 2020-01-26 14:15
https://github.com/microsoft/vscode/issues/89295

**Comment by Gruntfuggly** [comment] 2020-01-30 15:15
Looks like it will be fixed in the next release.

**Comment by Gruntfuggly** [comment] 2020-02-09 13:11
I'm going to close this now as it looks like it's been fixed in the latest vscode, although there still seem to be other issues, but not as bad.

**Closed by Gruntfuggly** 2020-02-09 13:11 UTC
Labels: fix-pending
