### ISSUE TITLE
See your TODO count in the status bar..

### ISSUE THREAD

**Issue by Yzrsah** [Gruntfuggly/todo-tree#102] opened 2018-12-04 10:35 UTC
I would love it if you could see a TODO count in your status bar.
Cause we want those TODO and Fixme to go to 0 :)
Being able to see a count in the status bar is a good reminder to reduce the number.
There could be a setting to show a merged count or show separate counts for each tag.

**Comment by Gruntfuggly** [comment] 2018-12-04 12:09
That could be useful - I'll add it as an option.

**Comment by WORMSS** [comment] 2018-12-10 09:01
I came to ask the same, but for maybe 
![image](https://user-images.githubusercontent.com/1384537/49721421-1686f680-fc5a-11e8-8385-179fc7bf585f.png)
or even 
![image](https://user-images.githubusercontent.com/1384537/49721454-2272b880-fc5a-11e8-93bb-e41384e579ac.png)
I don't mind which..

**Comment by Gruntfuggly** [comment] 2018-12-10 16:05
Hi - the status bar is almost ready.  Unfortunately adding to the tree view can only be done by adding something to the item labels, so it can't be shown exactly like you have it.

So it could show something like:
`TODO (5)`
but it won't look as nice.

**Comment by WORMSS** [comment] 2018-12-10 17:10
To be honest, it's actually what I thought myself, but I can only do so much with mspaint at short notice. Lol

**Comment by Gruntfuggly** [comment] 2018-12-11 23:08
Latest version has counts in the status bar - you can chose total or per tag from the settings, or click the status bar to toggle.

**Comment by Gruntfuggly** [comment] 2018-12-11 23:10
If I add counters to the tree itself, would you expect them on all nodes with children, or just the grouped tag nodes (as in your top picture)?

**Comment by WORMSS** [comment] 2018-12-12 05:11
I would have thought the grouped tags, because in other ways it's mostly going to be `filename.ext (1)`  seeing hundreds of them seems a little unneeded. But I am sure someone out there that will disagree with me.

**Comment by beebase** [comment] 2018-12-13 07:16
@Gruntfuggly  Thanks for adding this feature in the latest release 👍 
```
// What to show in the status bar - nothing, total count, or counts per tag
  "todo-tree.statusBar": "none"
```

Would it make sense to add an array as an option to filter the counts in the statusbar?
```"todo-tree.statusBar":['TODO', 'BUG",...]```
(i have like 15 tags filling up the entire statusbar when using 'counts per tag'

**Comment by Gruntfuggly** [comment] 2018-12-13 09:04
I would prefer not to have another list of the tags in the settings - I'm not particularly happy with how it is at the moment with a list of tags and then the custom highlights needing to reference each tag again, as it opens up possible configuration errors.

How about another option: "top three", showing the three tags with the highest number of counts? The full list could still be shown in the tooltip?

**Comment by Gruntfuggly** [comment] 2018-12-13 09:16
@WORMSS Looks like the latest vscode release supports a new description property - I'll have a look, but this might make putting the counters on the nodes look nice.

**Comment by beebase** [comment] 2018-12-14 14:55
> How about another option: "top three", showing the three tags with the highest number of counts? The full list could still be shown in the tooltip?

That would work fine.

I see what you mean with 'possible configuration errors'
Maybe "todo-tree.customHighlight" should be merged into "todo-tree.tags' like:
```
todo-tree.tags : {
  'TODO' : {
    "iconColour": "grey",
    "background": "grey",
    "showInStatusBar" : true,
    ...
    ...
```
But then again, I have no clue how much that would break existing code. 😉

**Comment by WORMSS** [comment] 2018-12-22 17:55
Thank you very much @gruntfuggly

I have finished work until the new year, but I will set a reminder to turn the setting on.

**Closed** 2019-01-01 21:37 UTC
Labels: enhancement, fixed

**Comment by WORMSS** [comment] 2019-01-03 11:45
@Gruntfuggly I can confirm it works and looks lovely.
![image](https://user-images.githubusercontent.com/1384537/50636189-158d7000-0f4d-11e9-88df-cfafc4daf55b.png)
