### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mdomenici** [Gruntfuggly/todo-tree#495] opened 2021-04-15 13:51 UTC
[Gruntfuggly.todo-tree-unresponsive.cpuprofile.txt](https://github.com/Gruntfuggly/todo-tree/files/6318490/Gruntfuggly.todo-tree-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `todo-tree`
- Extension Version: `0.0.211`
- OS Version: `Linux x64 5.8.0-49-generic`
- VS Code version: `1.55.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/tmp/Gruntfuggly.todo-tree-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by Gruntfuggly** [comment] 2021-04-15 13:54
Please see #478

**Comment by Marsfan** [comment] 2021-09-22 21:32
@Gruntfuggly I have noticed a couple of things in the output that this extension does that make this a much worse issue than it could be, and should be patched to reduce resource load

1. **todo-tree** still watches files in folder that are excluded in `todo-tree.filtering.excludeGlobs`. For example, I have the added `**/.tox` to my global `todo-tree.filtering.excludeGlobs`, yet in the output I am still seeing a large number of messages in **todo-tree**'s output log about files in the _.tox_ being changed.
  yet I still see ms
2. **todo-tree** is writing lots of redundant temporary files in workspace storage, specifically _%appdata%/Code/User/workspaceStorage/{workspaceID}/Gruntfuggly.todo-tree_ where _{workspaceID}_ is the GUID of the workspace being scanned. It seems that for every single file that **todo-tree** scans, it writes a temporary file to the project workspace storage that has nothing in it but the regex that is used to search for items. I don't know what a temp file with the regex is needed in the first place, the regex should just be stored in a variable.

**Comment by Gruntfuggly** [comment] 2021-09-23 07:54
Please could you post your settings so I can try to reproduce these issues. Do you have `todo-tree.general.enableFileWatcher` enabled?

**Comment by Gruntfuggly** [comment] 2021-09-23 08:01
The temp file is used as a safer way to pass the regex to ripgrep, otherwise the extension has to do a lot of escaping to pass some of the special characters in the regex. You can disable this by setting `todo-tree.ripgrep.usePatternFile` to false, however, it should automatically clean up the temp file when the search has finished.

**Comment by Marsfan** [comment] 2021-09-30 20:48
@Gruntfuggly Sorry for taking so long to post this. I have been very busy. 

> You can disable this by setting `todo-tree.ripgrep.usePatternFile` to false, however, it should automatically clean up the temp file when the search has finished.


I will try setting the `todo-tree.ripgrep.usePatternFile` to `false`. My issue is not with them being persistent, but with the fact that it creates and deletes so many. Maybe in the future it could only create a single temp file, instead of a new one for every single file it scans? 




> Please could you post your settings so I can try to reproduce these issues. Do you have `todo-tree.general.enableFileWatcher` enabled?

Below are all of the todo-tree settings defined in my _settings.json_ file. All others remain at default.

<details>
<summary> <b>todo-tree settings</b> </summary>

```json
{
    "todo-tree.filtering.excludeGlobs": [
        "**/node_modules",
        "**/.svn",
        "**/.git",
        "**/.mypy-cache",
        "**/__pycache__",
        "**/.pytest_cache",
        "**/.tox"
    ],
    "todo-tree.filtering.includeHiddenFiles": true,
    "todo-tree.general.enableFileWatcher": true,
    "todo-tree.general.tags": [
        "NOTE",
        "TODO",
        "FIXME",
        "DEBUG",
        "INFO"
    ],
    "todo-tree.highlights.customHighlight": {
        "DEBUG": {
            "background": "green",
            "fontWeight": 700,
            "foreground": "white",
            "icon": "bug",
            "iconColour": "green",
            "type": "tag"
        },
        "FIXME": {
            "background": "red",
            "fontWeight": 700,
            "foreground": "white",
            "icon": "alert",
            "iconColour": "yellow",
            "type": "tag"
        },
        "INFO": {
            "background": "blue",
            "fontWeight": 700,
            "foreground": "white",
            "icon": "info",
            "iconColour": "cyan",
            "type": "tag"
        },
        "NOTE": {
            "background": "blue",
            "fontWeight": 700,
            "foreground": "white",
            "icon": "info",
            "iconColour": "cyan",
            "type": "tag"
        },
        "TODO": {
            "background": "FFBD2A",
            "fontWeight": 700,
            "foreground": "black",
            "icon": "check",
            "iconColour": "green",
            "type": "tag"
        }
    },
    "todo-tree.highlights.enabled": true,
    "todo-tree.highlights.useColourScheme": true,
    "todo-tree.regex.regex": "((//|#|<!--|;|/\\*|\\^)\\s*($TAGS)|^\\s*- \\[ \\])",
    "todo-tree.general.debug": true,
}
```

**Comment by Gruntfuggly** [comment] 2021-10-02 14:50
The issue you are seeing is due to the file watcher being enabled - every time a file changes it will scan that file (and generate the pattern file). Unless files are changing outside of VSCode, you really don't need the file watcher to be enabled. If you do enable it you could set a more restrictive pattern.

I should really remove the feature because it causes more problems that it solves.

In normal use (without the file watcher) the pattern file is only generated once when the whole tree is scanned.

**Comment by Marsfan** [comment] 2021-10-04 16:13
@Gruntfuggly Ok. I suppose I don't fully understand the purpose of the File Watcher then. I assumed that it also applied for inside VS Code. i.e. if I file is modified inside code, it updates the todo tree. But if I understand what you are saying, even if I disable the watcher, editing files inside code will automatically update the tree?

**Comment by Gruntfuggly** [comment] 2021-10-05 18:16
The extension automatically detects change to files within the editor (which can be disabled if needed). The file watcher is intended to detect changes if you have other processes changing files (maybe from a task or a build process). It can only work within the workspace too - not across your whole disk.

As I said - it's not really that useful - I should probably add a big warning if it's enabled! 😁

**Comment by Gruntfuggly** [comment] 2021-10-05 20:20
The auto refresh should just refresh the current file when you change it. There is also a manual refresh button on the titlebar which refreshes the entire project.

If you really need a periodic refresh, then it probably does make sense to use the file watcher - but you should probably limit it to the files you're expecting to change.

**Comment by Luxcium** [comment] 2022-10-14 11:57
I decided to go « Monorepo style » and I noticed a problem: 

![Screenshot_000001_20221014_075516](https://user-images.githubusercontent.com/42672814/195841017-b29961a4-8a57-446a-b3cf-36444ca1b39f.png)
Above my editor in the taskbar I have a graph that shows CPU usage... it took me a long moment to troubleshoot this issue... it seems that it's caused by one of my favorite extensions and I do not want to disable Todo Tree...

*What should I od now...*

**Comment by Gruntfuggly** [comment] 2023-02-16 10:15
As the file watcher functionality has now been removed, I'm going to close this. Please see https://github.com/Gruntfuggly/todo-tree/issues/723 for details of the replacement settings. Hopefully everything is covered, but raise a new issue if you need to.

**Closed by Gruntfuggly** 2023-02-16 10:15 UTC
