### ISSUE TITLE
having todo tags like `???` and `!!!` breaks the extension

### ISSUE THREAD

**Issue by MartinP7r** [Gruntfuggly/todo-tree#158] opened 2019-05-01 08:32 UTC
using the default regex, using ??? and !!! as tags in not possible without escaping. doing so within the settings.json, like `"\\!\\!\\!", "\\?\\?\\?"` did lead to my CPU going into overdrive 😱and VSCode to freeze up.

**Comment by Gruntfuggly** [comment] 2019-05-01 12:49
Were you modifying the settings through the GUI? I've noticed that vscode updates the underlying settings as you type (maybe a second or so after you stop typing) which means that a partially entered regex can be passed to the extension.

I could change the extension so that the regex is not applied when it is changed, but that would mean users would have to manually refresh the tree.

**Comment by Gruntfuggly** [comment] 2019-05-01 13:03
OK, so I tried modifying the `settings.json` too and I see what you mean. I'll investigate whats going on...

**Comment by Gruntfuggly** [comment] 2019-05-01 14:33
The problem is the `???` which ends up matching literally everything. The extension attempts to escape the characters by converting them to using `\x5c` for the backslash in the regex passed to ripgrep, but this still matches everything instead of matching literal `?`.

This stems from a fix to allow backslashes in the tags - it looks like it might need to do something more clever to determine which backslashes to escape! :frowning_face:

**Comment by MartinP7r** [comment] 2019-05-02 01:05
Thanks for investigating. I got used to using `???` so it would be great if those show up in the tree. If I find the time I'll try and tinker around with the regex as well.

**Comment by SiriusStarr** [comment] 2019-08-04 18:10
I'd love to see a fix for this as well, as I'd like to use `?` as a tag, which is currently (seemingly?) impossible.

**Comment by Gruntfuggly** [comment] 2019-09-27 09:52
This should now work after fixing #218.

**Closed** 2019-10-11 12:41 UTC
Labels: bug, fixed
