### ISSUE TITLE
Bug in tree display - text after comment tags missing

### ISSUE THREAD

**Issue by mkizer** [Gruntfuggly/todo-tree#476] opened 2021-03-19 22:18 UTC
I just recently noticed that the text following a comment tag will disappear from the tree display. I've only tried this in a .yaml file, but I didn't notice an issue prior to the last update (or perhaps to the last VS Code update).

Example from a newly loaded project:
![a](https://user-images.githubusercontent.com/1832572/111847168-85396c80-88c5-11eb-88a6-7bc87943d833.png)

All of these entries contain some text following the comment tag, but a couple initially don't show anything.

After clicking on the first XXX tag in the tree, all of the text for the entries in that file disappear.
![b](https://user-images.githubusercontent.com/1832572/111847276-b87bfb80-88c5-11eb-899a-4202ec45ba5d.png)

I can refresh the tree and sometimes a couple of the entries will reappear.
All of the navigation and everything else still works.

**Comment by RoniPerson** [comment] 2021-03-20 08:29
I had the same problem. It helped to set scan mode to ``workspace only``. I have the problem since updating to v0.0.207. When downgrading to v0.0.206 everything worked fine for me.

**Comment by Gruntfuggly** [comment] 2021-03-20 10:25
I made some changes in 0.0.207 to tidy up how text after multiline comments is handled. It looks like I might have thrown away a bit too much!

Are you using the default regex? If not could you post your settings so I can try it here please. Also, if you could post a snippet of the code you expect it to match, that would be really useful.

**Comment by mkizer** [comment] 2021-03-20 14:18
Yes, just using the default (out-of-the-box) settings. The files show above are just .yaml files and the lines with the comments look like this:
```
# XXX - Use this Prod version as a base for any future RDS SQL Server template
# TODO - Write up deployment .md guide for RDS template with parameter file
# TODO - Pull parameters out and put in parameters file

# TODO - Write up deployment .md guide for RDS template with parameter file
# TODO - Pull parameters out and put in parameters file
```

**Comment by Gruntfuggly** [comment] 2021-03-20 14:24
Thanks - I'll take a look

**Comment by Gruntfuggly** [comment] 2021-03-20 14:27
OK - I can reproduce it. I'll try and get a fix this evening.

**Comment by Gruntfuggly** [comment] 2021-03-20 18:08
Should be fixed in 0.0.208. Please let me know if it's not.

**Comment by GitHunter0** [comment] 2021-03-20 19:17
I'm having the same problem, took me a while to give up and check if there was some issue here

**Comment by Gruntfuggly** [comment] 2021-03-20 19:18
Which version are you using?

**Comment by nikelborm** [comment] 2021-03-20 19:23
I have a similar, but different bug. 
When I swap the rows, the output in the tree breaks.
![Screenshot_20210320_221641](https://user-images.githubusercontent.com/29357907/111883143-886a5080-89ca-11eb-84c9-bb2dfe99bdb0.png)
![Screenshot_20210320_222223](https://user-images.githubusercontent.com/29357907/111883186-d0897300-89ca-11eb-9d39-c8934dd34d36.png)

**Comment by Gruntfuggly** [comment] 2021-03-20 19:25
Do you mind creating a new issue for that please - it will be easier to track. Also, can you tell me which version you are using and whether the problem exists with version 0.0.206?

**Comment by nikelborm** [comment] 2021-03-20 19:33
> Do you mind creating a new issue for that please - it will be easier to track. Also, can you tell me which version you are using and whether the problem exists with version 0.0.206?

I installed 0.0.208 and the bug was fixed for me.

**Comment by mkizer** [comment] 2021-03-20 19:38
> Should be fixed in 0.0.208. Please let me know if it's not.
Awesome, that did the trick. Everything looks like it is working for my use case.

Thanks, this is a super handy extension.

**Comment by Gruntfuggly** [comment] 2021-03-20 19:51
@GitHunter0 can you confirm if you are still seeing the issue with version 0.0.208?

**Comment by GitHunter0** [comment] 2021-03-20 19:56
> Which version are you using?

Now that I updated to 0.0.208 and reloaded, it is working fine, thank you

**Comment by Gruntfuggly** [comment] 2021-03-20 20:02
OK - let's just gloss over 0.0.207! 😀

**Comment by DEberhardt** [comment] 2021-03-21 10:30
no issue in 0.0.208 - I already forgot about 0.0.207 ;)

**Closed** 2021-03-24 16:59 UTC
Labels: fixed
