### ISSUE TITLE
Feature Request: Hide When Launching VSCode

### ISSUE THREAD

**Issue by meatch** [Gruntfuggly/todo-tree#427] opened 2021-01-25 01:38 UTC
If there is a way, I cannot find it. But essentially I only want TODO Tree to open when I am ready to use it.
It would seem every time I open. project its open by default and i have to hide it to get it out of my way.
I love the app, but only use it when I need to work on TODOs. not all the time.

I am on MacOS, TODO v0.0.196, VS Code Version: 1.52.1

**Comment by Gruntfuggly** [comment] 2021-01-25 08:47
There has been a setting `todo-tree.tree.hideTreeWhenEmpty` which hides the tree if there is nothing found.
Unfortunately there is a bug in VSCode which sometimes causes the extension to fail to start if the setting is currently enabled. This has been fixed in the Insiders version of VSCode so it should be fixed in the next release (which hopefully shouldn't be too long now). As soon as I can confirm it's working, I'll update the extension.

**Comment by meatch** [comment] 2021-01-25 16:33
Got it. Thanks for your consideration.

Other plugins I have do not expand in the sidebar when it launches. There will always be todos in codebases that need to be addressed later. And worth exploring like a backlog. But until i am ready to get to it, there should be an option (default IMHO) that has it collapsed when I open a project.

Again, I love this plugin. Hats off. And this is a minor user experience request. But certainly would elevate my experience.

My current workaround is to disable the plugin when not using it. I can then enable when I am ready to use it.

Cheers.

**Comment by Gruntfuggly** [comment] 2021-01-25 16:51
Where do you have the view? If I drag the view into the Explorer pane (I find it most useful there) and collapse it (by clicking the titlebar) it stays collapsed when I reopen the window?

**Comment by meatch** [comment] 2021-01-25 17:15
Yah, it's in the explorer pane for me too, I called it sidebar.

Weird now when I open my VS Code it remains collapsed. Not sure what I did differently. Maybe I toggled a setting in TODO TREE and just needed to relaunch VS Code for it to see the changes.

What was happening is it would show expanded when I would first open a project.

I will keep it on and see if it happens again. Hopefully its solved now.

![image](https://user-images.githubusercontent.com/3289961/105739808-5f0ed600-5eed-11eb-89f1-8cebd7dbfa76.png)

**Comment by Gruntfuggly** [comment] 2021-01-26 08:35
Ah - it will probably be expanded the first time you open a new workspace. There is no programatic control over the expansion state so it will always default to expanded first time a workspace is opened.

Once the new release of vscode comes out, I'll re-enable the hide setting and that _will_ apply to new workspaces.

**Comment by inliquid** [comment] 2021-02-15 12:14
> There is no programatic control over the expansion state so it will always default to expanded first time a workspace is opened.

Sorry, why do you say there is no control over it?

**All other plugins** have their outline views collapsed. Todo-tree, until some moment also had it collapsed. I'm pretty sure it can be fixed. Pretty annoying tbh, and yep, it makes me feel it would be better to disable extension until there is obvious need.

**Comment by Gruntfuggly** [comment] 2021-02-15 12:19
The view is collapsed when first created (on installation) but if you expand it, vscode remembers that it was expanded. There is nothing in the API to expand or collapse the view. If you know otherwise, please point me to the documentation.

Can you explain how it is annoying? When I open the window, if the view was previously collapsed it stays collapsed. Unless I have misunderstood? In which case please could you post a screen shot to show what you mean.

**Comment by inliquid** [comment] 2021-02-15 16:47
> The view is collapsed when first created (on installation) but if you expand it, vscode remembers that it was expanded
This is not the case. It's expanded _always_, by default, on first open of any new workspace.

**Comment by Gruntfuggly** [comment] 2021-02-15 16:50
Please can you post a screenshot? I've just reopened a workspace and this is what I see:
![image](https://user-images.githubusercontent.com/376658/107973967-d0521e00-6fad-11eb-9d3b-a30cf5fc607e.png)

**Comment by inliquid** [comment] 2021-02-15 16:54
Like this:

![изображение](https://user-images.githubusercontent.com/6797881/107974374-8f670300-6fc7-11eb-8d92-9ad68203d5ee.png)

**Comment by Gruntfuggly** [comment] 2021-02-15 16:56
Oh wait - any **new workspace** ? Yes - that is the default behaviour.  

Please see the first two posts of this issue - the intention is that under normal conditions (ie until the VSCode bug was fixed) that the tree is hidden unless there are any TODOs present. If there are, the tree is shown expanded, which I think would be the expected behaviour.

In the next release, this will be the case. In the meantime, I'm afraid you will have to manually collapse it.

Alternatively, you can move the tree back into the activity bar itself, where it will have its own view.

**Comment by inliquid** [comment] 2021-02-15 17:04
> If there are, the tree is shown expanded, which I think would be the expected behaviour.

I agree with OP here. I don't want to see anything expanded unless I decide to look at todos or whatever it is. Right now, first thing I do in every new VS Code window is collapsing this view. This is annoying. I don't care are there any TODOs or not. There would be plenty of them in any big enough project.

**Comment by Gruntfuggly** [comment] 2021-02-15 17:05
Please drag the view back into the activity bar.

**Comment by inliquid** [comment] 2021-02-15 17:06
I don't want this either.

**Comment by Gruntfuggly** [comment] 2021-02-15 17:07
Sorry, I don't understand. If you don't want to see it, why not put it in the activity bar? That way you will only see it when you click on it?

**Comment by Gruntfuggly** [comment] 2021-02-15 17:09
As the bug in VSCode has been fixed, I'll push a release tonight which hides the view if there is nothing in the tree.

**Comment by inliquid** [comment] 2021-02-15 17:11
> Sorry, I don't understand. If you don't want to see it, why not put it in the activity bar? That way you will only see it when you click on it?

I want to have expandable view on this pane, but I want it to be collapsed until I decide to look what's in there. No matter if there are todos in the project, If I didn't want it at all I would not use an extension and not complain here.

**Comment by Gruntfuggly** [comment] 2021-02-15 17:24
Moving the view to the activity bar doesn't get rid of it - it's a single click to show the todos, the same as clicking the title bar to expand it if it's in the explorer pan.

I'm sorry, but I won't change the default behaviour of collapsing the view initially - you are the first person to have asked for that, and I feel that most people would prefer to see the TODOs when opening a workspace, rather than having to expand it each time.

What you are asking for is not technically possible without forcing the view to be present in the explorer pane by default. By design it has its own view in the activity bar, on installation - this is in keeping with most custom tree view extensions. It can be dragged into the explorer pane (or anywhere else in the GUI) but as soon as you drag it, it will become expanded to fit anyway.

As I said above - I'll push a change to hide the view when it is empty.

**Comment by Gruntfuggly** [comment] 2021-02-15 17:27
BTW, sorry, but it can't be controlled by a setting either - it can only be hard coded in the extension's `package.json` file. If it was, I would gladly add it.

**Comment by inliquid** [comment] 2021-02-15 17:38
> you are the first person

Well, actually in this thread I'm a second person.

**Comment by Gruntfuggly** [comment] 2021-02-15 17:41
They wanted it hidden, not collapsed. Hiding is possible, and was the old functionality (which is about to be fixed).

**Comment by inliquid** [comment] 2021-02-15 17:42
>They wanted it hidden, not collapsed. Hiding is possible, and was the old functionality (which is about to be fixed).

Not sure:

>Other plugins I have do not expand in the sidebar when it launches. There will always be todos in codebases that need to be addressed later. And worth exploring like a backlog. But until i am ready to get to it, there should be an option (default IMHO) that has it collapsed when I open a project.

I don't understand why it could not be possible, when other plugins remain collapsed and I remember that this was previously same for Todo Tree as well.

**Comment by Gruntfuggly** [comment] 2021-02-15 18:13
Todo tree has never started collapsed by default - the only way to do it is by adding `"visibility":"collapsed"` in the package.json, and I only found out about that today.

Even so, that only applies to new workspaces, the first time they are opened and I still think it is more desirable to show the todos initially than hide them. 

As I said, the only way that plugins can remain collapsed is if they default to being present in the Explorer pane, and I don't think this is the right thing to do since VSCode allowed extensions to add their own containers in the activity bar.

The history is that when the extension was first written, you could only put custom tree views in the explorer pane. New functionality was added to VSCode to allow custom containers to be used in the activity bar, so an option was added to put it in both. When they then added the view drag and drop functionality, it didn't make sense to have two simultaneous views, so the explorer one was removed. However, to prevent existing users from wondering where the view had gone, if they previously had the view showing in the explorer pane, on update it was moved automatically into the explorer pane. That doesn't happen for new installs.

If you want to change the extension for your own use, you could try the following:

1. navigate to `.vscode/extensions/gruntfuggly.todo-tree-0.0.196` (or wherever the extensions are if you're on Windows)
2. open `package.json` in an editor
3. remove the "viewContainers" section
4. change "todo-tree-container" to "explorer" at line 34
5. add `"visibility": "collapsed"` at line 39

So it looks like this:
```
    .
    .
    .
        "activationEvents": [
		"*"
	],
	"main": "./dist/extension",
	"contributes": {
		"views": {
			"explorer": [
				{
					"id": "todo-tree-view",
					"name": "%todo-tree.container.name%",
					"when": "!todo-tree-is-empty",
                                        "visibility": "collapsed"
				}
			]
		},
		"menus": {
			"view/title": [
				{
					"command": "todo-tree.exportTree",
					"when": "view =~ /todo-tree/ && todo-tree-show-export-button == true",
					"group": "navigation@1"
				},
    .
    .
    .
```
Then reload. I think that will work.

Note: You'll have to repeat this each time the extension gets updated. 

Or you could fork the project and make the change.

**Comment by Gruntfuggly** [comment] 2021-02-24 20:06
Just uploaded v0.0.197 which re-enables the `hideTreeWhenEmpty` flag.

**Closed** 2021-03-03 12:05 UTC
Labels: fixed
