### ISSUE TITLE
Disabling the highlighting when inspecting a file in git

### ISSUE THREAD

**Issue by emanuelenardi** [Gruntfuggly/todo-tree#466] opened 2021-03-15 18:15 UTC
Issue Type: Feature Request

I'd like to disable the highlighting when inspecting a file in git.

There is too much color, also the file on the right is highlighted, whereas the one on the left it is not.
I'd like to see only the red and green colours by git.

![image](https://user-images.githubusercontent.com/15109661/111200954-8e26f700-85c2-11eb-90ba-2ab8b7079dd5.png)

**Comment by Gruntfuggly** [comment] 2021-03-16 12:29
That may not be possible, but I'll look into it. If I can't get it to work using the file "type", I could add a button to the status bar to enable/disable the highlights. Not perfect, but would at least work.

The issue with only highlighting one side should have been fixed in version 0.0.205 - can you check if you  are on the latest version? Although that will make this issue worse, sorry.

**Comment by emanuelenardi** [comment] 2021-03-17 13:53
The extension is up to date.

```
Name: Todo Tree
Id: gruntfuggly.todo-tree
Description: Show TODO, FIXME, etc. comment tags in a tree view
Version: 0.0.205
Publisher: Gruntfuggly
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree
```

**Comment by Gruntfuggly** [comment] 2021-03-17 13:59
Yes, I think the issue isn't the same. At the moment there doesn't seem to be any way to know if the current editor window is showing diffs. The editor just appears to the API like a normal editor window.

I'm adding an option to toggle the highlights by clicking the status bar item. 

If you set `todo-tree.general.statusBar` to anything except `none` and then set `todo-tree.general.statusBarClickBehaviour` to `toggle highlights` it will switch them on and off.

Not perfect, but it may be the best I can do at the moment.

**Comment by Gruntfuggly** [comment] 2021-03-17 20:28
Added in version 0.0.206

**Closed** 2021-03-21 11:57 UTC
Labels: enhancement, fixed
